# Change these first
owner: travellings-link # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Site
    url: https://www.travellings.cn
  - name: Member List
    url: https://list.travellings.cn
  - name: .link跳转页面
    url: https://travellings.link/
  - name: API
    url: https://api.travellings.cn/random
    __dangerous__body_down_if_text_missing: '"success":true,'
    headers:
      - "Referer: https://api.travellings.cn"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: stat.travellings.cn
  # baseUrl: /your-repo-name
  logoUrl: https://www.travellings.cn/assets/travelling.png
  name: 开往 Travellings
  introTitle: 开往服务状态监测
  introMessage: 我们通过监测服务状态，及时通知维护组修复来保证开往的可用性。
  navbar:
    - title: Status
      href: /
    - title: Travelling
      href: https://www.travellings.cn/go.html
